server:
  port: 9002
spring:
  application:
    name: SINHVIEN-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttemps: 3
        waitDuration: 1s
